version: "3"

networks:
  gitea:
    external: false

services:
  
  gitserver:
    image: gitea/gitea:1.16.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - APP_NAME="Gitea:A personal git repository for CI/CD"
      - DOMAIN="git.local"
      - SSH_DOMAIN="git.local"
      - SSH_PORT=8022
      - SSH_LISTEN_PORT=22
      - HTTP_PORT=8080                                # change gitea default to 8080
      - LFS_START_SERVER=true 
      - INSTALL_LOCK=true 
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=false 
    restart: always
    networks:
      - gitea
    volumes:
      - /vagrant_data/data/gitea:/data                # map vagrant_data to gitea's docker volumn 
      - /home/vagrant/.ssh/:/data/git/.ssh            # use vagrant-host's ssh config.
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
      - "8022:22"
  
  post_setup:                                              # init users.
    image: gitea/gitea:1.16.3
    depends_on:
      - gitserver
    volumes:
      - /vagrant_data/data/gitea:/data                # map vagrant_data to gitea's docker volumn 
      - /home/vagrant/.ssh/:/data/git/.ssh            # use vagrant-host's ssh config.
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
    networks:
      - gitea
    command: -c "gitea admin user create --username \"${GITEA_ADMIN}\" --password \"${GITEA_ADMIN_PASSWD}\" --email \"${GITEA_ADMIN_EMAIL}\" --admin" git
  # TODO: create account for drone.io
     