version: "3"

networks:
  gitea:
    external: false

services:
  
  gitserver:
    image: gitea/gitea:1.16.3
    container_name: gitea
    environment:
      - USER_UID=${GITEA_USER_UID}
      - USER_GID=${GITEA_USER_UID}
      - APP_NAME="${GITTEA_APP_NAME}"
      - DOMAIN=${GIT_SERVER_NAME} 
      - SSH_DOMAIN=${GIT_SERVER_NAME}
      - SSH_PORT=8022
      - SSH_LISTEN_PORT=22
      - HTTP_PORT=8080                                # change gitea default to 8080
      - LFS_START_SERVER=true 
      - INSTALL_LOCK=true 
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=false 
      - TZ=${TIMEZONE}
    restart: always
    networks:
      - gitea
    volumes:
      - /vagrant_data/data/gitea:/data                # map vagrant_data to gitea's docker volumn 
      - /home/vagrant/.ssh/:/data/git/.ssh            # use vagrant-host's ssh config.
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "git.local:${GIT_SERVER_IP}"
      - "ci.local:${CI_SERVER_IP}"
    ports:
      - ${GITTEA_SERVER_PORT:-8080}:8080
      - "8022:22"
  
  post_setup:                                              # init users.
    image: gitea/gitea:1.16.3
    depends_on:
      - gitserver
    volumes:
      - /vagrant_data/data/gitea:/data                # map vagrant_data to gitea's docker volumn 
      - /home/vagrant/.ssh/:/data/git/.ssh            # use vagrant-host's ssh config.
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=${GITEA_USER_UID}
      - USER_GID=${GITEA_USER_UID}
      - TZ=${TIMEZONE}
    networks:
      - gitea
    entrypoint: /bin/su                             # can NOT run gitea as root even add user via 
    command: -c "gitea admin user create --username \"${GITEA_ADMIN}\" --password \"${GITEA_ADMIN_PASSWD}\" --email \"${GITEA_ADMIN_EMAIL}\" --admin --access-token >/data/gitea_admin_resp.txt" git
  